spring:
  application:
    name: AUTH-SERVICE
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

redis:
  host: "redis"
  port: "6380"