services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5434/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=emirhan
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_JAVA_OPTS=-Xmx512m
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube
    depends_on:
      - postgres


  postgres-sonarqube:
    container_name: postgres-sonarqube
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=emirhan
      - POSTGRES_DB=sonarqube
      - PGDATA=/data/postgres
    ports:
      - 5434:5434
    volumes:
      - ./postgres-sonarqube:/data/postgres
    command: -p 5434
    networks:
      - sonarqube
    restart: always


networks:
  sonarqube:

volumes:
  sonarqube:
  postgres-sonarqube: