services:
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ./redis:/data
    expose:
      - "${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: --port ${REDIS_PORT}
    networks:
      - redis
    restart: always


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    expose:
      - "${RABBITMQ_PORT}"
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    networks:
      - rabbitmq
    restart: always


  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    expose:
      - "${ZIPKIN_PORT}"
    ports:
      - "${ZIPKIN_PORT}:${ZIPKIN_PORT}"
    networks:
      - zipkin
    restart: always


  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB:
        - auth-service
        - user-service
        - product-service
        - sale-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emirhan
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    networks:
      - postgres
    restart: always


  service-registry:
    container_name: service-registry
    image: emirhantuygun/service-registry:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "${SERVICE_REGISTRY_PORT}"
    ports:
      - "${SERVICE_REGISTRY_PORT}:${SERVICE_REGISTRY_PORT}"
    networks:
      - registry
      - zipkin
    depends_on:
      - zipkin


  api-gateway:
    container_name: api-gateway
    image: emirhantuygun/api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "${API_GATEWAY_PORT}"
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    networks:
      - registry
      - redis
      - zipkin
    depends_on:
      - service-registry
      - redis
      - zipkin


  product-service:
    container_name: product-service
    image: emirhantuygun/product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - registry
      - postgres
      - redis
      - rabbitmq
      - zipkin
    depends_on:
      - service-registry
      - api-gateway
      - redis
      - postgres
      - rabbitmq
      - zipkin


  sale-service:
    container_name: sale-service
    image: emirhantuygun/sale-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - registry
      - postgres
      - rabbitmq
      - zipkin
    depends_on:
      - service-registry
      - api-gateway
      - postgres
      - product-service
      - rabbitmq
      - zipkin


  report-service:
    container_name: report-service
    image: emirhantuygun/report-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - registry
      - zipkin
    depends_on:
      - service-registry
      - api-gateway
      - sale-service
      - zipkin


  auth-service:
    container_name: auth-service
    image: emirhantuygun/auth-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - registry
      - postgres
      - redis
      - rabbitmq
      - zipkin
    depends_on:
      - service-registry
      - api-gateway
      - postgres
      - redis
      - rabbitmq
      - zipkin


  user-service:
    container_name: user-service
    image: emirhantuygun/user-management-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - registry
      - postgres
      - rabbitmq
      - zipkin
    depends_on:
      - service-registry
      - api-gateway
      - postgres
      - auth-service
      - rabbitmq
      - zipkin


networks:
  postgres:
  registry:
  redis:
  rabbitmq:
  zipkin:



