services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-sonarqube:${POSTGRES_SONARQUBE_PORT}/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=emirhan
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_JAVA_OPTS=-Xmx512m
    ports:
      - "${SONARQUBE_PORT}:${SONARQUBE_PORT}"
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube
    depends_on:
      - postgres-sonarqube


  postgres-sonarqube:
    container_name: postgres-sonarqube
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=emirhan
      - POSTGRES_DB=sonarqube
      - PGDATA=/data/postgres
    ports:
      - "${POSTGRES_SONARQUBE_PORT}:${POSTGRES_SONARQUBE_PORT}"
    volumes:
      - ./postgres-sonarqube:/data/postgres
    command: -p ${POSTGRES_SONARQUBE_PORT}
    networks:
      - sonarqube
    restart: always


networks:
  sonarqube:

volumes:
  sonarqube:
  postgres-sonarqube: