package com.bit.usermanagementservice.dto;

public enum UserStatus {
    USER_CREATED_SUCCESSFULLY,
    USER_NOT_CREATED,
    USER_FOUND_SUCCESSFULLY,
    USER_NOT_FOUND,
    USERS_FOUND_SUCCESSFULLY,
    USERS_NOT_FOUND,
    USER_UPDATED_SUCCESSFULLY,
    USER_NOT_UPDATED,
    USER_DELETED_SUCCESSFULLY,
    USER_NOT_DELETED,
}
