spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

jwt:
  signerKey: "4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c"
  authorities-key: "roles"

database:
  url: "jdbc:postgresql://postgres-auth:5436/auth-service"
  username: "postgres"
  password: "emirhan"

route:
  auth: "http://auth-service:8081"
  user: "http://user-service:8082"
  product: "http://product-service:8083"
  sale: "http://sale-service:8084"
  report: "http://report-service:8085"


