spring:
  application:
    name: REPORT-SERVICE

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

gateway:
  host: localhost
  port: 8080

endpoint:
  sale-service:
    get-sale: "sales/{id}"
    get-all-sales: "sales"
    get-deleted-sales: "sales/deleted"
    get-all-sales-filtered-and-sorted: "sales/filteredAndSorted"

receipt:
  font-path: "fonts/scoreboard.ttf"
  image-path: "/static/images/32bit.png"
  location: "KEMALPASA, ESENTEPE CAMPUS, 54050"
  city: "SERDIVAN/SAKARYA"
  phone-number: "0264 295 54 54"

chart:
  font-path:
    light: "fonts/rubik-light.ttf"
    regular: "fonts/rubik-regular.ttf"
  image-path:
    gemini: "/static/images/gemini.png"
    symbol: "/static/images/symbol.png"

gemini:
  api-key: ${GEMINI_API_KEY}