spring:
  application:
    name: SALE-SERVICE

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

gateway:
  host: "localhost"
  port: 8080

endpoint:
  product-service:
    get-product: products/{id}
    are-enough-products-in-stock: stock