spring:
  application:
    name: SALE-SERVICE
  rabbitmq:
    host: localhost

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

gateway:
  host: localhost
  port: 8080

endpoint:
  product-service:
    get-product: products/{id}
    check-stock: products/stock
    return-products: products/return

rabbitmq:
  exchange: reduce-stock-exchange
  queue: reduce-stock-queue
  routingKey: reduce.stock