spring:
  application:
    name: PRODUCT-SERVICE
  rabbitmq:
    host: localhost

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

company:
  name: 32bit

rabbitmq:
  exchange: reduce-stock-exchange
  queue: reduce-stock-queue
  routingKey: reduce.stock

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0