spring:
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

gateway:
  host: api-gateway
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
