spring:
  application:
    name: USER-SERVICE

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

default-roles: CASHIER, MANAGER, ADMIN

gateway:
  host: localhost
  port: 8080

