spring:
  application:
    name: USER-SERVICE
  rabbitmq:
    host: localhost

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

default-roles: CASHIER, MANAGER, ADMIN

gateway:
  host: localhost
  port: 8080

rabbitmq:
  exchange: user-exchange
  queue:
    create: user-queue-create
    update: user-queue-update
    delete: user-queue-delete
    deletePermanent: user-queue-delete-permanent
    restore: user-queue-restore
  routingKey:
    create: user.create
    update: user.update
    delete: user.delete
    deletePermanent: user.delete.permanent
    restore: user.restore