spring:
  application:
    name: USER-SERVICE
  rabbitmq:
    host: localhost

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

default-roles: CASHIER, MANAGER, ADMIN

endpoint:
  auth-service:
    create: "auth/create"
    update: "auth/update/{id}"
    restore: "auth/restore/{id}"
    delete: "auth/delete/{id}"
    delete-permanently: "auth/delete/permanent/{id}"

gateway:
  host: localhost
  port: 8080

rabbitmq:
  exchange: user-exchange
  queue:
    create: user-queue-create
    update: user-queue-update
    delete: user-queue-delete
    deletePermanent: user-queue-delete-permanent
    restore: user-queue-restore
  routingKey:
    create: user.create
    update: user.update
    delete: user.delete
    deletePermanent: user.delete.permanent
    restore: user.restore